language: java
jdk: oraclejdk9
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

addons:
  postgresql: "9.6"

services:
  - postgresql

before_install:
  - psql -c "create user ilya with password 'qwerty123';" -U postgres
  - psql -c "create database ilyadb;" -U postgres
  - psql -c "grant all on database ilyadb to ilya;" -U postgres

#deploy:
#  provider: heroku
#  api_key:
#    secure: $HEROKU_API_KEY
#  app: BroForce-02-2018
#  on:
#    repo: BatrSens/BroForce-02-2018
#    branch: master
#  skip_cleanup: true